/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiSettingPanel: typeof import('./src/components/dashboard/AiSettingPanel.vue')['default']
    CategoryContextMenu: typeof import('./src/components/note/CategoryContextMenu.vue')['default']
    CategoryTree: typeof import('./src/components/note/CategoryTree.vue')['default']
    CategoryTreeNode: typeof import('./src/components/note/CategoryTreeNode.vue')['default']
    ChangePasswordDialog: typeof import('./src/components/note/dialogs/ChangePasswordDialog.vue')['default']
    CreateNotebookDialog: typeof import('./src/components/note/dialogs/CreateNotebookDialog.vue')['default']
    CreateNoteDialog: typeof import('./src/components/note/dialogs/CreateNoteDialog.vue')['default']
    DeleteNotebookDialog: typeof import('./src/components/note/dialogs/DeleteNotebookDialog.vue')['default']
    DocBreadcrumb: typeof import('./src/components/doc/DocBreadcrumb.vue')['default']
    DocCategory: typeof import('./src/components/doc/DocCategory.vue')['default']
    DocFormDialog: typeof import('./src/components/dashboard/DocFormDialog.vue')['default']
    DocHeader: typeof import('./src/components/doc/DocHeader.vue')['default']
    DocHome: typeof import('./src/components/doc/DocHome.vue')['default']
    DocNote: typeof import('./src/components/doc/DocNote.vue')['default']
    DocSidebar: typeof import('./src/components/doc/DocSidebar.vue')['default']
    DocsPanel: typeof import('./src/components/dashboard/DocsPanel.vue')['default']
    DocToc: typeof import('./src/components/doc/DocToc.vue')['default']
    DocTreeNode: typeof import('./src/components/doc/DocTreeNode.vue')['default']
    DynamicIcon: typeof import('./src/components/DynamicIcon.vue')['default']
    ExportDialog: typeof import('./src/components/note/dialogs/ExportDialog.vue')['default']
    HelpPanel: typeof import('./src/components/dashboard/HelpPanel.vue')['default']
    HomePanel: typeof import('./src/components/dashboard/HomePanel.vue')['default']
    ImportDialog: typeof import('./src/components/note/dialogs/ImportDialog.vue')['default']
    InfoDialog: typeof import('./src/components/note/dialogs/InfoDialog.vue')['default']
    LoadingBarGuard: typeof import('./src/components/LoadingBarGuard.vue')['default']
    MoveDialog: typeof import('./src/components/note/dialogs/MoveDialog.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NotebookSwitcher: typeof import('./src/components/note/NotebookSwitcher.vue')['default']
    NoteContextMenu: typeof import('./src/components/note/NoteContextMenu.vue')['default']
    NoteEditor: typeof import('./src/components/note/NoteEditor.vue')['default']
    NoteList: typeof import('./src/components/note/NoteList.vue')['default']
    NoteListItem: typeof import('./src/components/note/NoteListItem.vue')['default']
    NoteMetaBar: typeof import('./src/components/note/NoteMetaBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareDialog: typeof import('./src/components/note/dialogs/ShareDialog.vue')['default']
    ShareList: typeof import('./src/components/note/ShareList.vue')['default']
    SiteSettingPanel: typeof import('./src/components/dashboard/SiteSettingPanel.vue')['default']
    SystemPanel: typeof import('./src/components/dashboard/SystemPanel.vue')['default']
    TemplatePanel: typeof import('./src/components/dashboard/TemplatePanel.vue')['default']
    UserHeader: typeof import('./src/components/note/UserHeader.vue')['default']
    UsersPanel: typeof import('./src/components/dashboard/UsersPanel.vue')['default']
    VditorEditor: typeof import('./src/components/note/VditorEditor.vue')['default']
    VersionHistoryDialog: typeof import('./src/components/note/dialogs/VersionHistoryDialog.vue')['default']
  }
}
